[tool.poetry]
name = "python backend platform"
version = "0.1.0"
description = "Sic Parvis Magna"
authors = ["Luis Zenteno"]

[tool.poetry.dependencies]
django = "^3.1.5"
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
